# Thông tin sinh viên

## - **Họ tên:** Trần Nguyên Huân
## - **Mã số sinh viên:** 21127050
## - **Lớp:** 21CLC03

In [96]:
import numpy as np
import sympy as sp
import math

 # <font face="gotham" color="purple">Ma trận chéo hóa được</font>
 ---

Một ma trận vuông $A$ cỡ $n\times n$ được gọi là chéo hóa được hay không khiếm khuyết nếu tồn tại một ma trận khả nghịch P sao cho: 
$$
A=PDP^{-1}
$$
Và hơn nữa, các cột của $P$ là các vectơ riêng độc lập tuyến tính của $A$, và các giá trị riêng tương ứng của nó nằm trên đường chéo của $D$.Nói cách khác, $A$ có thể chéo hóa được khi và chỉ khi số chiều của cơ sở không gian riêng là $n$.

 # <font face="gotham" color="purple">Thuật toán chéo hóa ma trận</font>
 ---


> **Bước 1.** Giải phương trình đặc trưng $det(λI - A) = 0$ để tìm các trị riêng.
> - Nếu $det(λI - A) = 0$ không phân rã hoàn toàn thành tích các đa thức dạng bậc 1 (dạng (*)) thì $A$ không chéo hóa được.
> - Nếu $det(λI - A) = (λ - λ_{1})^{r_{1}} ... (λ - λ_{k})^{r_{k}}$ (*) thì sang bước 2.
>
> **Bước 2.** Với mỗi trị riêng $λ_i$ tìm một cơ sở $S_i$ cho không gian riêng $E_{λ_i} = \{x \in R^n | (λ_{i}I - A)x = 0\}$
> - Nếu tồn tại không gian riêng có $dim E_{λ_i} < r_{i}$ thì kết luận $A$ không chéo được. 
> - Nếu $dim E_{λ_i} = r_{i}, \forall i = 1,2,...,k$, thì sang bước 3.
>
> **Bước 3.** Đặt $S = S_1 \cup ... \cup S_k = \{ u_1, ..., u_n\}$, thì S là một cơ sở của không gian $R^n$.
>
> Đặt $P = (u_1 ... u_n)$, ta có $P^{-1}AP = diag(λ_{1} ... λ_{1} ... λ_{k} ... λ_{1})$, với $λ_{i}$ lặp $r_i$ lần


 ## <font face="gotham" color="green">Thuật toán Power Iteration để tìm trị riêng - vector riêng (tham khảo thêm)</font>
 ---

**Giải thích thuật toán**:
Thuật toán Power Iteration được sử dụng để tìm giá trị riêng cực đại của ma trận vuông và vector riêng tương ứng của nó. Quá trình lặp sẽ dẫn đến giá trị riêng ước lượng càng chính xác với mỗi bước lặp, và vector riêng ước lượng cũng được cập nhật tương ứng. Khi thuật toán hội tụ, giá trị riêng ước lượng và vector riêng ước lượng tương ứng sẽ cung cấp một ước lượng của giá trị riêng cực đại và vector riêng tương ứng của ma trận A. Thuật toán này thường được sử dụng cho các ma trận lớn và thưa có giá trị riêng lớn nhất cách biệt rõ ràng với các giá trị riêng còn lại.

**Đầu vào:** Ma trận vuông $A$ (kích thước $n\times n$), và một vector bất kỳ $x_0$ có độ dài bằng số cột của ma trận $A$.

**Đầu ra:** Giá trị riêng ước lượng cực đại $λ_{max}$ và vector riêng ước lượng tương ứng $v_{max}$ của ma trận $A$.

> **Bước 1. Khởi tạo**: Chọn vector bắt đầu $x = x_0$ (có thể là vector ngẫu nhiên hoặc vector kiểm định).
>
> **Bước 2. Lặp**:
>
> - Thực hiện chuẩn hóa vector x: $x = \frac{x}{{\|x\|}}$ ($||x||$ là norm của vector x).
> - Tính vector mới y bằng cách nhân ma trận $A$ với vector x: $y = A * x$.
> - Cập nhật giá trị riêng ước lượng $λ_{max}: λ_{max} = (x^T * y) / (x^T * x)$.
> - Cập nhật vector riêng ước lượng $v_{max}: v_{max} = x$.
>
> **Bước 3. Kiểm tra điều kiện dừng**: Thoát khỏi vòng lặp nếu giá trị riêng ước lượng hội tụ đủ chính xác hoặc số vòng lặp đã đạt tới một ngưỡng nhất định.
>
> **Bước 4. Kết quả**: Trả về giá trị riêng ước lượng cực đại $λ_{max}$ và vector riêng ước lượng tương ứng $v_max$ của ma trận $A$.

 ## <font face="gotham" color="green">Thuật toán ứng dụng của QR-Decomposition để tìm trị riêng - vector riêng (tham khảo thêm)</font>
 ---

**Giải thích thuật toán**:
Thuật toán này là một phương pháp sử dụng phép phân rã QR để ước lượng các giá trị riêng và vector riêng của một ma trận vuông $A$. Ý tưởng chính của thuật toán là sử dụng phép phân rã QR lặp đi lặp lại trên ma trận $A$, cùng với việc cập nhật ma trận $Ak$ và ma trận đếm tổng hợp $QQ$, để tìm các giá trị riêng gần đúng và các vector riêng tương ứng.

**Đầu vào:** Ma trận vuông $A$ (kích thước $n\times n$) và số lần lặp iterations.

**Đầu ra:** Mảng chứa các giá trị riêng và ma trận chứa các vector riêng tương ứng của ma trận $A$.

> **Bước 1. Khởi tạo**: Sao chép ma trận $A$ vào ma trận $Ak$. Tạo ma trận đơn vị $QQ$ với kích thước $n\times n$.
>
> **Bước 2. Lặp**: Trong mỗi lần lặp, chúng ta thực hiện các bước sau:
>
> - Lấy phần tử cuối cùng của đường chéo chính của ma trận $Ak$ và gán vào biến $s$. Điều này tương đương với lấy giá trị riêng ước lượng tại lần lặp hiện tại.
> - Tạo ma trận $smult$ là ma trận đơn vị nhân với hằng số $s$. Ma trận này được sử dụng để trừ đi phần tử cuối cùng của đường chéo chính của $Ak$.
> - Thực hiện phép phân rã QR trên $Ak$ sau khi trừ đi ma trận $smult$: $Ak = QR - smult$. Phép phân rã QR phân tách ma trận $Ak$ thành hai ma trận $Q$ và $R$ sao cho $Ak = QR$.
> - Cập nhật ma trận $Ak: Ak = RQ + smult$. Bước này là để quay lại ma trận ban đầu ($Ak$) sau khi đã thực hiện phân rã $QR$.
> - Cập nhật ma trận $QQ: QQ = QQ * Q$. Điều này giúp tích lũy các ma trận Q được tính toán ở mỗi lần lặp, nhằm xây dựng ma trận chứa các vector riêng ước lượng tương ứng.
>
> **Bước 3. Kết quả**: Sau khi kết thúc vòng lặp, chúng ta trích xuất các giá trị trên đường chéo của ma trận $Ak$, đây là các giá trị riêng ước lượng gần đúng của ma trận $A$. Các vector riêng tương ứng ước lượng được lưu trong ma trận $QQ$.

**Lưu ý**: số lần lặp (iterations) được chọn lớn để đảm bảo thuật toán hội tụ đủ chính xác. Tuy nhiên, việc chọn một giá trị lớn cho iterations có thể làm tăng thời gian tính toán. Thuật toán này thường được sử dụng để ước lượng các giá trị riêng và vector riêng của ma trận lớn khi không cần tính toán chính xác đến mức cao nhất.

 ## <font face="gotham" color="green">Nghịch đảo ma trận (phục vụ tìm P_inverse)</font>

In [97]:
#utility functions serve invserse matrix 
def is_zero(x):
    return math.isclose(x, 0, abs_tol=1e-10)

def row_switch(A, i, k):
    "di <-> dk"
    A[i], A[k] = A[k], A[i]

def row_mul(A, i, alpha):
    "di = alpha*di"
    A[i] = [alpha*Aii for Aii in A[i]]

def row_add(A, i, k, alpha):
    "di = di + anpha*dk"
    A[i] = [0 if is_zero(Aii + alpha*Aki) else Aii + alpha*Aki for Aii, Aki in zip(A[i], A[k])]

def create_augmented_matrix_GJ(A):
    I = create_identity_matrix(len(A))
    return [Ai[:] + Ii for Ai, Ii in zip(A, I)]

# Gauss-Jordan elimination
def Gauss_Jordan(A):
    # Append unique matrix to A matrix
    augmented_A = create_augmented_matrix_GJ(A)

    n_row = len(A)
    n_col_A = len(A[0])

    row = col = 0

    while row < n_row:
        # Step 1: Identify the leftmost column that contains only zeros
        while col < n_col_A and all(is_zero(augmented_A[i][col]) for i in range(row, n_row)):
            col += 1
        if col == n_col_A:
            break
        
        # Step 2: Select the first row that contains non-zero coefficient
        pivot_row = row + [not is_zero(augmented_A[i][col]) for i in range(row, n_row)].index(True)
        row_switch(augmented_A, row, pivot_row)

        # Step 3: Leading 1 option
        row_mul(augmented_A, row, 1/augmented_A[row][col])

        # Step 4: Add an appropriate multiple of the current row to the other rows, so that the coefficients in the column col become 0
        for i in range(n_row):
            if i == row:
                continue
            
            multiplier = augmented_A[i][col]/augmented_A[row][col]
            row_add(augmented_A, i, row, -multiplier)

        row += 1

    return augmented_A

# Invert matrix using Gauss-Jordan
def invert_matrix_GJ(A):
    n_col_A = len(A[0])
    GJ_A = Gauss_Jordan(A)

    # Separate the left and right matrices from the output matrix after using Gauss-Jordan elimination
    lmatrix = [GJ_Ai[:n_col_A] for GJ_Ai in GJ_A]
    rmatrix = [GJ_Ai[n_col_A:] for GJ_Ai in GJ_A]

    # Determine whether the matrix is invertible
    if lmatrix[-1][-1] == 0:
        print('Singular matrix')
        return None

    return rmatrix



 ## <font face="gotham" color="green">Hàm Gauss_Elimination và hàm Back_Substitution (phục vụ giải hệ phương trình tuyến tính để tìm vector riêng)</font>

In [98]:
def Gauss_elimination(A):
    R = A.copy()
    n_row, n_col = len(R), len(R[0]) # kích thước ma trận
    row = col = 0
    while row < n_row:
        # Bước 1
        while col < n_col and all(is_zero(R[i][col]) for i in range(row, n_row)):
            col += 1
        if col == n_col: # đã có dạng bậc thang
            break
        
        # Bước 2 (chọn dòng đầu tiên có số hạng khác 0)
        pivot_row = row + [not is_zero(R[i][col]) for i in range(row, n_row)].index(True)
        row_switch(R, row, pivot_row)
        
        # Bước 3
        row_mul(R, row, 1/R[row][col])
            
        # Bước 4
        for i in range(row + 1, n_row):
            row_add(R, i, row, -R[i][col])
    
        # Bước 5
        row += 1
    return R

def back_substitution(R):
    "R là ma trận bậc thang của ma trận bổ sung của hệ phương trình Ax = b"
    n_row, n_col = len(R), len(R[0]) # kích thước ma trận R
    
    # vector nghiệm (danh sách theo thứ tự ẩn)
    sol = [None for _ in range(n_col - 1)]
    
    # Tìm dòng dưới cùng khác không
    row = n_row - 1
    while row >= 0 and all(is_zero(R[row][j]) for j in range(n_col)):
        row -= 1
    
    if row >= 0 and [not is_zero(R[row][j]) for j in range(n_col)].index(True) == n_col - 1:
        print("Hệ phương trình tuyến tính vô nghiệm") # vô nghiệm
        return None
    
    last_pcol = n_col - 1
    while row >= 0:
        pcol = [not is_zero(R[row][j]) for j in range(n_col)].index(True)
        for i in range(pcol, last_pcol): # các ẩn tự do
            sol[i] = sp.symbols(f"x{i + 1}")
        sol[pcol] = R[row][n_col - 1] - sum(R[row][j]*sol[j] for j in range(pcol + 1, n_col - 1))
        last_pcol = pcol
        row -= 1
    
    # Bổ sung các ẩn tự do từ 0 đến last_pcol - 1
    for i in range(0, last_pcol):
        sol[i] = sp.symbols(f"x{i + 1}")
    return sol

## <font face="gotham" color="green">Các hàm phụ hỗ trợ cho việc tìm trị riêng - vector riêng và chéo hóa ma trận</font>

In [108]:
def sort_eigenvalues_vectors(eigenvalues, eigenvectors):
    idx = sorted(range(len(eigenvalues)), key=lambda k: eigenvalues[k], reverse=True)
    sorted_eigenvalues = [eigenvalues[i] for i in idx]
    sorted_eigenvectors = [[eigenvectors[j][i] for i in idx] for j in range(len(eigenvectors))]
    return sorted_eigenvalues, sorted_eigenvectors

def create_diagonal_matrix(diagonal_values):
    n = len(diagonal_values)
    D = [[0.0] * n for _ in range(n)]
    for i in range(n):
        D[i][i] = diagonal_values[i]
    return D

def multiply_matrix_to_vector(matrix, vector):
    if len(matrix[0]) != len(vector):
        return None
    result = [0] * len(matrix)
    for i in range(len(matrix)):
        for j in range(len(vector)):
            result[i] += matrix[i][j] * vector[j]
    return result

def dot_product(vector1, vector2):
    """Calculate the dot product of two vectors."""
    return sum(v1 * v2 for v1, v2 in zip(vector1, vector2))

def normalize_vector(vector):
    """Normalize a vector (i.e., scale it to have a magnitude of 1)."""
    magnitude = (sum(v**2 for v in vector))**0.5
    return [v / magnitude for v in vector]

def transpose(matrix):
    n = len(matrix)
    m = len(matrix[0])
    return [[matrix[i][j] for i in range(n)] for j in range(m)]


def magnitude(vector):
    """
    Tính độ dài (độ lớn) của vector.
    """
    return sum(x**2 for x in vector)**0.5

#multiply 2 matrix
def dot(A, B):
    # Kiểm tra nếu số cột của ma trận A không bằng số hàng của ma trận B
    if len(A[0]) != len(B):
        raise ValueError("Số cột của ma trận A phải bằng số hàng của ma trận B.")
    
    # Khởi tạo ma trận kết quả với kích thước phù hợp
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    
    # Tính toán phép nhân ma trận
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    
    return result

def create_identity_matrix(size):
    matrix = [[0] * size for _ in range(size)]
    for i in range(size):
        matrix[i][i] = 1
    return matrix

def subtract(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if rows_A != rows_B or cols_A != cols_B:
        raise ValueError("The matrices must have the same dimensions for subtraction.")

    result = [[0 for j in range(cols_A)] for i in range(rows_A)]
    for i in range(rows_A):
        for j in range(cols_A):
            result[i][j] = A[i][j] - B[i][j]

    return result

def add(A, B):
    # Add matrix A and B
    rows = len(A)
    cols = len(A[0])

    result = [[0 for j in range(cols)] for i in range(rows)]
    for i in range(rows):
        for j in range(cols):
            result[i][j] = A[i][j] + B[i][j]
    return result

def copy_matrix(A):
    rows = len(A)
    cols = len(A[0])
    Ak = [[0 for j in range(cols)] for i in range(rows)]

    for i in range(rows):
        for j in range(cols):
            Ak[i][j] = A[i][j]

    return Ak

def create_identity_matrix_with_constant(n, s):
    # Tạo ma trận đơn vị với kích thước nxn và phần tử chéo chính bằng s
    identity_matrix = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        identity_matrix[i][i] = s
    return identity_matrix

def extract_diagonal(matrix):
    if not matrix:
        return []

    num_rows = len(matrix)
    num_cols = len(matrix[0])

    if num_rows != num_cols:
        raise ValueError("Matrix is not square, cannot extract diagonal.")

    return [matrix[i][i] for i in range(num_rows)]

def multiply_diagonal(matrix, number):
    # Kiểm tra ma trận có đúng là ma trận vuông hay không
    if not all(len(row) == len(matrix) for row in matrix):
        raise ValueError("Ma trận không phải là ma trận vuông.")

    # Nhân số vào đường chéo
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if i == j:  # Kiểm tra nếu đây là phần tử trên đường chéo
                matrix[i][j] *= number

    return matrix

 # <font face="gotham" color="purple">Trị riêng - Vector riêng</font>

## <font face="gotham" color="blue">Cách 1: Sử dụng phương pháp giải phương trình đặc trưng $det(A - λI) = 0$ (cách được hướng dẫn trong phần bài tập)</font>

In [109]:
def find_eigenvalues(matrix):
    n = matrix.shape[0]
    I = create_identity_matrix(n) # Ma trận đơn vị cùng kích thước với ma trận đầu vào
    lamda = sp.Symbol('lambda')  # Biến lambda đại diện cho giá trị riêng
    det_eq = determinant(subtract(matrix, multiply_diagonal(I, lamda)))  # Phương trình det(A - λI) = 0
    eigenvalues = sp.solve(det_eq, lamda)  # Giải phương trình det(A - λI) = 0 để tìm các giá trị riêng
    return eigenvalues

def find_eigenvectors(matrix, eigenvalues):
    eigenvectors = []
    updated_eigenvalues = [] 
    for eigenvalue in eigenvalues:
        # Tìm ma trận (A - λI) với giá trị riêng hiện tại 
        A_minus_lambdaI = matrix - eigenvalue * np.eye(matrix.shape[0])
        vector_size = len(A_minus_lambdaI)
        # Create the zero vector
        vector0 = create_zero_vector(vector_size)
        A_minus_lambdaI_list = [np_array.tolist() for np_array in A_minus_lambdaI]
        # Add the zero vector as a new row to the augmented matrix
        A_minus_lambdaI = create_augmented_matrix(A_minus_lambdaI_list, vector0)
        A_minus_lambdaI = Gauss_elimination(A_minus_lambdaI)
        eigenvector = back_substitution(A_minus_lambdaI)
        # Extract symbols from the expressions
        symbols_list = extract_symbols(eigenvector)
        # Generate the vals list
        vals = generate_vals(symbols_list)
        # Evaluate the eigen_vectors by replacing symbol following values (1,0,0), (0,1,0), ...
        eigenvector = evaluate_vectors(eigenvector, vals)
        for _ in range (len(eigenvector)):
            updated_eigenvalues.append(eigenvalue)
        eigenvectors.extend(eigenvector)
    return updated_eigenvalues, transpose(eigenvectors)

## <font face="gotham" color="blue">Cách 2:  Sử dụng thuật toán [Power iteration](https://en.wikipedia.org/wiki/Power_iteration) và Hotelling's Deflation [[1](https://web.stanford.edu/~lmackey/papers/deflation-nips08.pdf), [2](https://www.robots.ox.ac.uk/~sjrob/Teaching/EngComp/ecl4.pdf)]</font>

In [110]:
def eigen_power_iteration(A, n_iter=5000000, eps=1e-6):
    A = np.array(A)
    # Create a random vector
    b_k = np.random.rand(A.shape[1])
    b_k_pre = np.zeros(A.shape[1])

    # Repeat the process of finding an eigenvector for a maximum of n_iter times
    for _ in range(n_iter):
        # Calculate the dot product of matrix A and eigenvector
        numerator = multiply_matrix_to_vector(A, b_k)
        denominator = magnitude(numerator)

        b_k = scalar_multiply(1 / denominator, numerator)

        # Terminate the loop when the change in the vector is negligible
        if all(abs(x - y) < eps for x, y in zip(b_k, b_k_pre)):
            break

        b_k_pre = b_k

    # Find eigen value (Rayleigh quotient iteration)
    numerator = multiply_matrix_to_vector(A, b_k)
    lamb = dot_product(b_k, numerator) / dot_product(b_k, b_k)

    return lamb, b_k  # lamb: eigen value, b_k: eigen vector

def my_eigens_power_iteration(A, n_iter=5000000, eps=1e-6):
    eigenvalues = []
    eigenvectors = []

    n_rows = len(A)

    # Find all possible eigenvalues and eigenvectors
    for _ in range(n_rows):
        lamb, b_k = eigen_power_iteration(A, n_iter, eps)

        eigenvalues.append(lamb)
        eigenvectors.append(b_k)

        # Hotelling's deflation
        b_k = [x for x in b_k]
        A = [[A[i][j] - lamb * b_k[i] * b_k[j] for j in range(n_rows)] for i in range(n_rows)]

    return np.array(eigenvalues), np.array(transpose(eigenvectors))


## <font face="gotham" color="blue">Cách 3: Sử dụng ứng dụng của [QR-Decomposition](https://www.andreinc.net/2021/01/25/computing-eigenvalues-and-eigenvectors-using-qr-decomposition) </font>

In [111]:
def my_eigen_qr_practical(A, iterations=500000):
    Ak = copy_matrix(A)
    n = len(Ak)
    QQ = create_identity_matrix(n)
    for k in range(iterations):
        # s_k is the last item of the first diagonal
        s = Ak[-1][-1]
        smult = create_identity_matrix_with_constant(n, s)
        # pe perform qr and subtract smult
        Q, R = np.linalg.qr(subtract(Ak, smult))
        # we add smult back in
        Ak = add(dot(R,Q), smult)
        QQ = dot(QQ, Q)
    eigenvalues = extract_diagonal(Ak)  # Extract eigenvalues from the diagonal of Ak
    eigenvectors = QQ 
    return np.array(eigenvalues), np.array(eigenvectors)

In [112]:
#Các ma trận mẫu
A = np.array([[4, 0, 1], 
             [-2, 1, 0], 
             [-2, 0, 1]])

B = np.array([[3, -2, 0],
             [-2, 3, 0],
             [0, 0, 5]])

C = np.array([[-1, 3, -1],
             [-3, 5, -1],
             [-3, 3, 1]])


In [113]:
#Hàm dùng để đánh giá độ chính xác của kết quả chéo hóa
def is_close(A, B, eps=10e-3):
    return np.all(np.abs(A - B) < eps)

# <font face="gotham" color="purple">Chéo hóa ma trận</font>
---

## <font face="gotham" color="green">Các hàm phụ phục vụ chéo hóa</font>

In [114]:
def create_augmented_matrix(matrix, vector):
    augmented_matrix = []
    for i in range(len(matrix)):
        augmented_matrix.append(matrix[i] + [vector[i]])
    return augmented_matrix

def create_zero_vector(size):
    return [0] * size

def extract_symbols(expressions):
    symbols_list = set()
    for expr in expressions:
        if isinstance(expr, int):
            continue  # Skip integers (constants) as they have no symbols
        symbols_list.update(expr.free_symbols)
    return sorted(list(symbols_list), key=lambda x: x.name)

def generate_vals(symbols):
    vals = []
    num_symbols = len(symbols)
    for i in range(num_symbols):
        val_combinations = []
        for j in range(num_symbols):
            if i == j:
                val_combinations.append((symbols[j], 1))
            else:
                val_combinations.append((symbols[j], 0))
        vals.append(val_combinations)
    return vals

def evaluate_vectors(expressions, vals):
    vectors = []
    for val_combinations in vals:
        vector = []
        for expr in expressions:
            if isinstance(expr, int):
                vector.append(expr)  # Add the constant value directly to the vector
            else:
                evaluated_expr = expr.subs(val_combinations)
                if evaluated_expr.is_number:
                    vector.append(evaluated_expr)
        if vector and not all(elem == 0 for elem in vector):  # Skip the vector if it's all zeros
            vectors.append(vector)
    return vectors


def determinant(matrix):
    matrix = sp.Matrix(matrix)
    if matrix.shape == (2, 2):
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

    det = 0
    for col in range(matrix.shape[1]):
        submatrix = matrix[1:, :col].row_join(matrix[1:, col + 1:])
        det += (-1) ** col * matrix[0, col] * determinant(submatrix)

    return det

## <font face="gotham" color="green">Hàm chính thực hiện chéo hóa ma trận</font>

In [115]:
def diagonalization_matrix(matrix):
    
    # eigenvalues, eigenvectors = my_eigens_power_iteration(matrix)
    # eigenvalues, eigenvectors = my_eigen_qr_practical(matrix, 1000)

    # Sort eigenvalues and eigenvectors
    eigenvalues = find_eigenvalues(matrix)
    eigenvalues, eigenvectors = find_eigenvectors(matrix, eigenvalues)
    sorted_eigenvalues, sorted_eigenvectors = sort_eigenvalues_vectors(eigenvalues, eigenvectors)

    # Create diagonal matrix D from sorted eigenvalues
    D = create_diagonal_matrix(sorted_eigenvalues)

    # Calculate matrix P from sorted eigenvectors
    P = sorted_eigenvectors

    # Calculate matrix P_inv (P inverse)
    P_inv = invert_matrix_GJ(P)

    return np.array(P), np.array(D), np.array(P_inv)


In [116]:
# Find diagonalization matrices P, P_inv, and D
P, D, P_inv = diagonalization_matrix(B)
result = dot(dot(P, D), P_inv)

# Verify the result A = P * D * P_inv
print("Matrix A:")
print(B)
print("Matrix P:")
print(P)
print("Matrix D:")
print(D)
print("Matrix P_inv:")
print(P_inv)
print("A = P * D * P_inv:")
print(np.array(result))

Matrix A:
[[ 3 -2  0]
 [-2  3  0]
 [ 0  0  5]]
Matrix P:
[[-1.00000000000000 0 1.00000000000000]
 [1 0 1]
 [0 1 0]]
Matrix D:
[[5 0.0 0.0]
 [0.0 5 0.0]
 [0.0 0.0 1]]
Matrix P_inv:
[[-0.500000000000000 0.500000000000000 0]
 [0 0 1]
 [0.500000000000000 0.500000000000000 0]]
A = P * D * P_inv:
[[3.00000000000000 -2.00000000000000 0]
 [-2.00000000000000 3.00000000000000 0]
 [0 0 5]]


Kiểm tra lại kết quả $P^{-1} * A * P$ có bằng $D$ hay không

In [117]:
is_close(D, dot(dot(P_inv, B), P))

True

# <font face="gotham" color="purple">Thư viện `np.linalg`</font>

## <font face="gotham" color="blue">Tìm trị riêng - vector riêng sử dụng thư viện numpy</font>

In [132]:
A = np.array([[3, -2, 0],
             [-2, 3, 0],
             [0, 0, 5]])

np_eigenvalues, np_eigenvectors = np.linalg.eig(A)

np_eigenvalues, np_eigenvectors

(array([5., 1., 5.]),
 array([[ 0.71,  0.71,  0.  ],
        [-0.71,  0.71,  0.  ],
        [ 0.  ,  0.  ,  1.  ]]))

## <font face="gotham" color="blue">Chéo hóa ma trận sử dụng thư viện numpy</font>

In [133]:
def my_diag(A):
    # Find eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(A)
    
    # Order eigenvectors by their corresponding eigenvalues
    sorted_idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_idx]
    eigenvectors = eigenvectors[:, sorted_idx]
    
    P_matrix = eigenvectors
    P_inv_matrix = np.linalg.inv(P_matrix)
    D_matrix = np.diag(eigenvalues)
    
    return P_matrix, D_matrix, P_inv_matrix

In [134]:
P, D, P_inv = my_diag(A)
(P, D, P_inv)

(array([[ 0.  ,  0.71,  0.71],
        [ 0.  , -0.71,  0.71],
        [ 1.  ,  0.  ,  0.  ]]),
 array([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 1.]]),
 array([[ 0.  ,  0.  ,  1.  ],
        [ 0.71, -0.71,  0.  ],
        [ 0.71,  0.71,  0.  ]]))

In [135]:
D, P_inv @ A @ P

(array([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 1.]]),
 array([[ 5.,  0.,  0.],
        [ 0.,  5., -0.],
        [ 0., -0.,  1.]]))

In [136]:
is_close(D, P_inv @ A @ P)

True

# <font face="gotham" color="purple">Thư viện SymPy thực hiện chéo hóa</font>

In [137]:
A = sp.Matrix([[3, -2, 0],
             [-2, 3, 0],
             [0, 0, 5]])



In [138]:
P, D = A.diagonalize()

In [139]:
P

Matrix([
[1, -1, 0],
[1,  1, 0],
[0,  0, 1]])

In [140]:
D

Matrix([
[1, 0, 0],
[0, 5, 0],
[0, 0, 5]])

In [141]:
P**-1

Matrix([
[ 1/2, 1/2, 0],
[-1/2, 1/2, 0],
[   0,   0, 1]])

In [142]:
P*D*P**-1

Matrix([
[ 3, -2, 0],
[-2,  3, 0],
[ 0,  0, 5]])

In [143]:
P*D*P**-1 == A

True

## <font face="gotham" color="green">Sử dụng ```is_diagonalizable``` trong SymPy để kiểm tra ma trận A có chéo hóa được hay không</font>

In [144]:
A.is_diagonalizable()

True

# <font face="gotham" color="purple">Một số ứng dụng của chéo hóa</font>

1. **Giải hệ phương trình tuyến tính**: Chéo hóa ma trận giúp chuyển đổi hệ phương trình tuyến tính thành một hệ phương trình đơn giản hơn để dễ dàng giải. Khi ma trận được chéo hóa, việc giải hệ phương trình trở nên dễ dàng hơn và tốn ít thời gian hơn.

2. **Tính định thức**: Việc chéo hóa ma trận giúp tính định thức một cách dễ dàng hơn. Khi ma trận được chéo hóa, định thức của nó chính bằng tích của các phần tử nằm trên đường chéo chính.

3. **Tính nghịch đảo ma trận**: Đối với ma trận vuông và khả nghịch, chéo hóa ma trận giúp tìm nghịch đảo của nó dễ dàng hơn. Nghịch đảo ma trận là một phép toán quan trọng trong nhiều ứng dụng trong toán học và khoa học máy tính.

4. **Giải các bài toán tối ưu**: Chéo hóa ma trận là một bước quan trọng trong việc giải các bài toán tối ưu, như phân tích thành phần chính (PCA) và tối ưu hóa lồi.

5. **Xử lý dữ liệu và ảnh**: Trong xử lý dữ liệu và xử lý ảnh, việc chéo hóa ma trận có thể giúp giảm chiều dữ liệu và giảm thông tin không cần thiết, từ đó giúp tăng tốc độ xử lý và giảm độ phức tạp tính toán.

6. **Hệ thống đám mây**: Chéo hóa ma trận cũng được ứng dụng trong việc xây dựng hệ thống đám mây (cloud system) để tối ưu hóa tài nguyên và quản lý mạng.

7. **Xử lý tín hiệu và âm thanh**: Trong xử lý tín hiệu và âm thanh, chéo hóa ma trận có thể được sử dụng để nén dữ liệu và giảm thiểu thông tin không cần thiết trong tín hiệu và âm thanh.



# <font face="gotham" color="purple">Mô tả ý tưởng thực hiện và mô tả các hàm chính</font>

1. Hàm `find_eigenvalues(matrix)`: Hàm này tìm trị riêng của ma trận đầu vào bằng cách sử dụng phương trình đặc trưng det(A - λI) = 0, trong đó A là ma trận đầu vào, `λ` biểu diễn giá trị riêng và `I` là ma trận đơn vị cùng kích thước với `A`.
    - Hàm trước tiên tạo một ma trận đơn vị I có cùng kích thước với ma trận đầu vào.
    - Hàm định nghĩa một biến ký hiệu lamda để biểu diễn trị riêng (sử dụng Symbols trong thư viện Sympy).
    - Sau đó, tính toán phương trình định thức det(A - λI). (sử dụng thêm `determinant`, `dot`, `substract` thực hiện biểu thức) 
    - Cuối cùng, hàm `solve` của thư viện **SymPy** để giải phương trình định thức theo hình thức biểu diễn toán học để tìm các giá trị riêng và trả về chúng.
2. Hàm `find_eigenvectors(matrix, eigenvalues)` được viết để tìm các vector riêng tương ứng với danh sách các giá trị riêng cho một ma trận đầu vào. Cách thức hàm hoạt động như sau:
    - Tạo ma trận `(A - λI)` bằng cách trừ giá trị của eigenvalue đã tìm trong hàm `find_eigenvalues` với ma trận đơn vị `I` có kích thước tương ứng với ma trận `matrix`. Ma trận `(A - λI)` này được tạo để tìm các vector riêng tương ứng với giá trị riêng này.
    - Thêm vector không vào như một hàng mới của ma trận `(A - λI)` để lập ma trận bổ sung (augmented matrix)
    - Sử dụng hàm `Gauss_elimination` đã làm trong đồ án **Gauss** để rút gọn ma trận `(A - λI)` về dạng bậc thang (có tham khảo trong file Lab 1_Toan UDTK_Gauss_after.html)
    - Sử dụng hàm `back_substitution` để giải phương trình tuyến tính tìm ra các nghiệm tổng quát.
    - Thay các kí hiệu $(x1, x2, x3,...)$ bằng các giá trị lần lượt theo thứ tự là $(1,0,0, ...), (0,1,0, ...), ...$ để tìm ra các vector riêng
    - Với bao nhiêu số vector riêng tạo ra từ trị riêng đó thì thêm vào list `update_eigenvalues` bấy nhiêu số trị riêng đó.
    - Cuối cùng hàm trả về `update_eigenvalues` (list các trị riêng) và ma trận chuyển vị của danh sách các vector riêng (các vector riêng được tạo thành cột của ma trận P)
3. Hàm `diagonalization_matrix(matrix)`: Hàm này thực hiện đường chéo hóa ma trận.
    - Gọi các hàm `find_eigenvalues(matrix)` và `find_eigenvectors(matrix, eigenvalues)` để tìm giá trị riêng và vector riêng.
    - Sắp xếp các giá trị riêng và các vector riêng tương ứng. (theo thứ tự giảm dần)
    - Tạo ma trận chéo `D` từ các giá trị riêng đã sắp xếp.
    - Tính ma trận `P` từ các vector riêng đã sắp xếp.
    - Tính ma trận nghịch đảo `P_inv` của ma trận `P`. (sử dụng hàm `invert_matrix_GJ` đã làm trong đồ án **Gauss – Jordan** để thực hiện nghịch đảo ma trận)
    - Cuối cùng trả ra `P`, `P_inv`, `D`
