## Thông tin sinh viên

- **Họ tên:** Trần Nguyên Huân
- **Mã số sinh viên:** 21127050
- **Lớp:** 21CLC03

## Tóm tắt phép khử Gauss - Jordan (Nguồn: trong file Lab 2_ToanUDTK_before)
---
Tìm một dạng bậc thang của ma trận $A = (a_{ij}) ∈ M_{m×n}(R).$

**Khử Gauss** (Gaussian elimination) là một cách biến đổi tương đương dòng đưa ma trận về dạng bậc thang. Thuật giải gồm các bước:

> **Bước 1.** Kiểm tra các số hạng từ dòng i đến dòng n của cột thứ i. Nếu chúng gồm toàn số 0, kết luận ma trận A không khả nghịch và giải thuật chấm dứt. Ngược lại, đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới dòng thứ j về dòng thứ i.
> 
> **Bước 2.** Với số hạng ở dòng thứ i là $a≠0$, nhân dòng i với $\frac{1}{a}$ để nhận được số 1 (nằm trên đường chéo của A)
> 
> **Bước 3.** Cộng một bội số thích hợp của dòng i với các dòng khác dòng i để biến các số hạng trên cột i về số **0** (trừ số hạng nằm ở dòng i. Trở lại bước 1 cho dòng kế, $i = i + 1$.

Kết thúc giải thuật, ta nhận được ma trận $(I|A^{-1})$.



## Pseudo Code giải thuật Gauss - Jordan (Mô tả ý tưởng)
---
**Input**: Ma trận vuông A.

**Output**: Ma trận nghịch đảo của A nếu có, hoặc thông báo "Ma trận không khả nghịch".

1. Khởi tạo ma trận đơn vị I có cùng kích thước với A.
2. Tạo ma trận mở rộng (A|I).
3. For i từ 0 đến (số hàng của A - 1):
     - Tìm hàng pivot: pivot_row = i.
       While phần tử tại cột i của hàng pivot bằng 0:
         pivot_row += 1.
         Nếu pivot_row = (số hàng của A), ma trận không khả nghịch, return "Ma trận không khả nghịch".
     - Hoán đổi hàng pivot và hàng i trong ma trận mở rộng.
     - Chia hàng pivot cho phần tử tại cột i để đưa phần tử đó về giá trị 1.
     - Áp dụng phép biến đổi Gauss-Jordan để đưa phần tử tại vị trí (i, i) về giá trị 1:
       For j từ 0 đến (số hàng của A - 1):
         If j != i:
           Trừ đi phần tử tại cột i của hàng j với phần tử tại cột i của hàng i nhân với phần tử tại vị trí (i, i) trong ma trận mở rộng.
4. Trích xuất ma trận nghịch đảo từ ma trận mở rộng (cột từ (số hàng của A) đến (2*(số hàng của A) - 1)).

**Note**: Giải thuật Gauss-Jordan sử dụng để tìm ma trận nghịch đảo của ma trận vuông. Nếu ma trận không khả nghịch, tức là không tồn tại ma trận nghịch đảo.


In [48]:
import numpy as np

def inverse(A):
    n = len(A)

    # Khởi tạo ma trận đơn vị I
    I = np.identity(n)

    # Tạo ma trận mở rộng (A|I)
    augmented_matrix = np.concatenate((A, I), axis=1)

    # Áp dụng phép biến đổi Gauss-Jordan
    for i in range(n):
        # Tìm hàng chứa phần tử khác không tại cột i
        pivot_row = i
        while augmented_matrix[pivot_row, i] == 0:
            pivot_row += 1

            # Nếu không tìm thấy hàng phù hợp, ma trận không khả nghịch
            if pivot_row == n:
                print("Ma trận không khả nghịch")
                return None

        # Hoán đổi hàng pivot về vị trí i
        augmented_matrix[[i, pivot_row]] = augmented_matrix[[pivot_row, i]]

        # Chia hàng pivot cho phần tử tại vị trí i để đưa phần tử đó về giá trị 1
        augmented_matrix[i] /= augmented_matrix[i, i]

        # Biến các số hàng trên cột j khác i về số 0
        for j in range(n):
            if j != i:
                augmented_matrix[j] -= augmented_matrix[j, i] * augmented_matrix[i]

    # Trích xuất ma trận nghịch đảo từ ma trận mở rộng
    inverse_A = augmented_matrix[:, n:]

    return inverse_A


## Một số test cases để chạy thử 

In [49]:
# Trường hợp ma trận khả nghịch 
A1 = np.array([[1, 1.5, -1.2],
              [2, 3.7, 8],
              [3.5, 2.5, 4]])

inverse(A1)




array([[-0.15142691, -0.26208503,  0.47874199],
       [ 0.58241118,  0.23878858, -0.30285381],
       [-0.23150844,  0.08008154,  0.02038439]])

In [50]:
# Trường hợp ma trận khả nghịch 
A2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

inverse(A2)


array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [51]:
# Trường hợp ma trận không khả nghịch 
B = np.array([[3, 2, 3],
              [2, 1, 3],
              [3, 2, 3]])
               
inverse(B)


Ma trận không khả nghịch


## Mở rộng một số hàm và phương thức tương ứng của thư viện và thực hiện để thực hiện tương tự hàm inverse() bên trên


### NumPy: NumPy là một thư viện mạnh mẽ cho tính toán khoa học và số học trong Python. Có thể sử dụng numpy.linalg.inv() để tính toán ma trận nghịch đảo. Ví dụ:

In [52]:
# Trường hợp ma trận khả nghịch 
A1 = np.array([[1, 1.5, -1.2],
              [2, 3.7, 8],
              [3.5, 2.5, 4]])

np.linalg.inv(A1)

array([[-0.15142691, -0.26208503,  0.47874199],
       [ 0.58241118,  0.23878858, -0.30285381],
       [-0.23150844,  0.08008154,  0.02038439]])

In [53]:
# Trường hợp ma trận khả nghịch
import numpy as np
A2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])
np.linalg.inv(A2)

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

***Đối với trường hợp ma trận không khả nghịch hàm np.linalg.inv() sẽ xảy ra lỗi.***

## Pseudo thuật toán tìm ma trận nghịch đảo có kết hợp định thức và ma trận phụ (Mô tả ý tưởng)
**Input**: Ma trận vuông A.

**Output**: Ma trận nghịch đảo của A nếu có, hoặc thông báo "Ma trận không khả nghịch".

1. Tính định thức của ma trận A: `det_A = np.linalg.det(A)`.
2. Kiểm tra det_A có bằng 0 hay không:
   - Nếu det_A = 0, in thông báo "Ma trận không khả nghịch" và trả về None.
3. Tính kích thước của ma trận A: `n = A.shape[0]`.
4. Tạo ma trận phụ adj_A có kích thước (n, n) và các phần tử ban đầu là 0.
5. For i từ 0 đến (n-1):
   - For j từ 0 đến (n-1):
     - Tạo ma trận minor bằng cách xóa hàng i và cột j từ ma trận A: `minor = np.delete(np.delete(A, i, axis=0), j, axis=1)`.
     - Tính giá trị cofactor cho phần tử A[i, j]: `cofactor = (-1)^(i+j) * np.linalg.det(minor)`.
     - Gán giá trị cofactor cho phần tử adj_A[j, i].
6. Tính ma trận nghịch đảo inv_A bằng cách chia từng phần tử của adj_A cho det_A: `inv_A = adj_A / det_A`.
7. Trả về ma trận nghịch đảo inv_A.

**Note**: Thuật toán này tính ma trận nghịch đảo bằng cách sử dụng ma trận phụ (adjoint matrix). Nếu ma trận không khả nghịch, tức là det_A = 0, thuật toán sẽ in thông báo "Ma trận không khả nghịch" và trả về None.


In [54]:
import numpy as np

def inverse_matrix(A):
    # Tính định thức của ma trận A
    det_A = np.linalg.det(A)

    # Kiểm tra ma trận A có khả nghịch hay không
    if det_A == 0:
        print("Ma trận không khả nghịch")
        return None

    # Tính kích thước của ma trận A
    n = A.shape[0]

    # Tạo ma trận phụ (adjoint matrix)
    adj_A = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            # Tính ma trận phụ của phần tử A[i, j]
            minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
            cofactor = (-1) ** (i + j) * np.linalg.det(minor)
            adj_A[j, i] = cofactor

    # Tính ma trận nghịch đảo bằng cách chia ma trận phụ cho định thức
    inv_A = adj_A / det_A

    return inv_A

In [55]:
# Trường hợp ma trận khả nghịch 
A1 = np.array([[1, 1.5, -1.2],
              [2, 3.7, 8],
              [3.5, 2.5, 4]])

inverse(A1)

array([[-0.15142691, -0.26208503,  0.47874199],
       [ 0.58241118,  0.23878858, -0.30285381],
       [-0.23150844,  0.08008154,  0.02038439]])

In [56]:
A2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

inverse_matrix(A2)


array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [57]:
# Trường hợp ma trận không khả nghịch 
B = np.array([[3, 2, 3],
              [2, 1, 3],
              [3, 2, 3]])
               
inverse(B)

Ma trận không khả nghịch


## ***Về phần mô tả ý tưởng đã trình bày trước mỗi code từng hàm thông qua pseudo code***

## Nhận xét về kết quả:
- Đối với trường hợp có khả nghịch, các kết quả trả ra từ các hàm chính (giải thuật khử gauss - jordan), kết quả từ hàm np.linalg.inv() của thư viện numpy và kết quả của phương thức sử dụng định thức kết hợp ma trận phụ là giống nhau. 
- Đối với trường hợp không khả nghịch thì hàm np.linalg.inv() sẽ thông báo lỗi, trong khi đó 2 phương thức còn lại sẽ trả ra thông báo "Ma trận không khả nghịch".